# Generated by Django 3.2.13 on 2022-06-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='secondary_graph',
            field=models.FilePathField(default='plotly.html', path='/graph'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='graph',
            field=models.FilePathField(default='plotly.html', path='/graph'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='preview_image',
            field=models.FilePathField(default='logo.png', path='/img'),
        ),
    ]
